### ISSUE TITLE
TLD Import & Pricing Sync problem

### ISSUE THREAD

**Issue by jsjcjsjc** [rrpproxy/whmcs-rrpproxy-registrar#86]
Hi
I get a problem regarding TLD Import & Pricing Sync, After click Sync button and wait a few minutes, there is nothing happend.
domain.com/admin/index.php?rp=/admin/utilities/tools/tldsync/import

after checking the log information, it looks there is something wrong
could you please help me with it ?

[![LFTCbF.jpg](https://s1.ax1x.com/2022/04/10/LFTCbF.jpg)](https://imgtu.com/i/LFTCbF)
[![LFT9DU.jpg](https://s1.ax1x.com/2022/04/10/LFT9DU.jpg)](https://imgtu.com/i/LFT9DU)

WHMCS 8.13
RRPproxy v1.3.0
PHP 7.4

**Comment by papakai** [comment]
Hey @jsjcjsjc,

thanks for addressing. I assigned it for review.

Best
Kai

**Comment by h9k** [comment]
Hi @jsjcjsjc , I believe the issue should be fixed in version 1.3.3, which has just been released.
Thanks for providing all the helpful details upfront, and sorry for the inconvenience.

**Comment by jsjcjsjc** [comment]
> Hi @jsjcjsjc , I believe the issue should be fixed in version 1.3.3, which has just been released. Thanks for providing all the helpful details upfront, and sorry for the inconvenience.

Thanks, but it still not work
[![LM4SLd.jpg](https://s1.ax1x.com/2022/04/13/LM4SLd.jpg)](https://imgtu.com/i/LM4SLd)

**Comment by jsjcjsjc** [comment]
Thanks for  your kind help, is there any provisional measures ?
I can't use this modules now.

**Comment by jsjcjsjc** [comment]
> Hi @jsjcjsjc,
> the problem is basically solved, but we have actually trouble with releasing for an unknown reason. We'll keep you posted.

Thanks for your kind help.
Please activate all of the TLDs in your test environment and test before release.
